version: '3.9'
services:
  db:
    image: postgres:16
    container_name: futcash_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: futcash
    ports:
      - "5432:5432"
    volumes:
      - futcash_pg_data:/var/lib/postgresql/data
volumes:
  futcash_pg_data: